version: '3.8'

services:
  mysql:
    image: mysql:8.1
    ports: 
      - 3307:3306
    container_name: mysql-user-service
    env_file:
      - .env
  
networks:
  humf-service-network:
    # external: true