version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports: 
      - 3307:3306
    container_name: mysql-kitchen-service
    env_file:
      - .env
  
  kitchen-service:
    build: ./
    container_name: kitchen-service
    env_file:
      - .env
    ports:
      - ${KITCHEN_SERVICE_PORT}:${KITCHEN_SERVICE_PORT}
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
    command: npm run start:dev
    networks:
      - default
      - humf-service-network

networks:
  humf-service-network:
    # external: true